version: "3.6"

services:
  python_sanic:
    image: python_sanic
    container_name: python_sanic_service
    build:
      context: python_sanic
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${SANIC_PORT}:${SANIC_PORT}"

  go_grpc:
    image: go_grpc
    container_name: go_grpc_service
    build:
      context: go_grpc
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${GO_GRPC_PORT}:${GO_GRPC_PORT}"

  go_mux:
    image: go_mux
    container_name: go_mux_service
    build:
      context: go_mux
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${GO_MUX_PORT}:${GO_MUX_PORT}"
